---
name: Upgrade Bundler Dependencies

on:
  schedule:
    - cron: '0 21 * * 5'
  workflow_dispatch:

jobs:
  upgrade_bundler_deps:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
      - run: bundle update --bundler && bundle update
        working-directory: macos

      # See: https://github.com/peter-evans/create-pull-request/tree/master#reference-example
      - name: create PR
        id: create_pull_request
        uses: peter-evans/create-pull-request@v8
        with:
          # See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          # See: https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-537478081
          token: ${{ secrets.PAT }}
          # See: https://github.com/peter-evans/create-pull-request/issues/593
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'upgrade bundler deps'
          title: 'upgrade bundler deps'
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)

            ---
            See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          branch: upgrade_bundler_deps
          delete-branch: true
          labels: |
            dependencies
            mac

      - name: enable auto-merge
        if: ${{ steps.create_pull_request.outputs.pull-request-number != '' }}
        run: gh pr merge ${{ steps.create_pull_request.outputs.pull-request-number }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.PAT }}
