---
name: Upgrade Flutter Dependencies

on:
  schedule:
    - cron: '0 21 * * 5'
  workflow_dispatch:

jobs:
  upgrade_flutter_dependencies:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2.21.0
        with:
          cache: true
      - run: flutter doctor -v
      - name: setup flutter channel
        shell: zsh {0} # See: https://github.com/actions/virtual-environments/issues/264#issuecomment-574032011
        run: ./scripts/setup_flutter.sh

      - name: setup flutter desktop
        shell: bash
        run: .github/scripts/macos/install_additional_requirements_for_flutter.sh

      - run: flutter pub get

      - run: flutter pub upgrade --major-versions --tighten

      # https://github.com/flutter/flutter/issues/73845#issue-785022394
      - run: rm macos/Podfile.lock && flutter build macos

      - name: upgrade external binary
        shell: zsh {0}
        run: ./scripts/fetch_libedax_assets.sh

      # See: https://github.com/peter-evans/create-pull-request/tree/master#reference-example
      - name: create PR
        id: create_pull_request
        uses: peter-evans/create-pull-request@v8
        with:
          # See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          # See: https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-537478081
          token: ${{ secrets.PAT }}
          # See: https://github.com/peter-evans/create-pull-request/issues/593
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'upgrade flutter dependencies'
          title: 'upgrade flutter dependencies'
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)

            ---
            See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          branch: upgrade_flutter_dependencies
          delete-branch: true
          labels: dependencies

      - name: enable auto-merge
        if: ${{ steps.create_pull_request.outputs.pull-request-number != '' }}
        run: gh pr merge ${{ steps.create_pull_request.outputs.pull-request-number }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.PAT }}
